# Load Data

In [6]:
import pandas as pd
pd.set_option('display.max_columns', 30)

import warnings
warnings.filterwarnings("ignore")

In [81]:
# Read in csv file
df = pd.read_csv("../assets/data/fake_jobs_clean.csv")
df.head(60)

,job_id,city,state/province,country,title,department,industry,function,salary_range,salary_provided,company_profile,description,requirements,benefits,benefits_provided,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,fraudulent
0,1,New York,NY,US,Marketing Intern,Marketing,NaN,Marketing,NaN,0,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,0,1,0,Other,Internship,NaN,0
1,2,Auckland,,NZ,Customer Service - Cloud Video Production,Success,Marketing and Advertising,Customer Service,NaN,0,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,1,0,1,0,Full-time,Not Applicable,NaN,0
2,3,Wever,IA,US,Commissioning Machinery Assistant (CMA),NaN,NaN,NaN,NaN,0,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,0,1,0,NaN,NaN,NaN,0
3,4,Washington,DC,US,Account Executive - Washington DC,Sales,Computer Software,Sales,NaN,0,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,1,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0
4,5,Fort Worth,FL,US,Bill Review Manager,NaN,Hospital & Health Care,Health Care Provider,NaN,0,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
5,6,,MD,US,Accounting Clerk,NaN,NaN,NaN,NaN,0,NaN,Job OverviewApex is an environmental consultin...,NaN,NaN,0,0,0,0,NaN,NaN,NaN,0
6,7,Berlin,BE,DE,Head of Content (m/f),ANDROIDPIT,Online Media,Management,20000-28000,1,"Founded in 2009, the Fonpit AG rose with its i...",Your Responsibilities: Manage the English-spea...,Your Know-How: ...,Your Benefits: Being part of a fast-growing co...,1,0,1,1,Full-time,Mid-Senior level,Master's Degree,0
7,8,San Francisco,CA,US,Lead Guest Service Specialist,NaN,NaN,NaN,NaN,0,Airenvy’s mission is to provide lucrative yet ...,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",Competitive Pay. You'll be able to eat steak e...,1,0,1,1,NaN,NaN,NaN,0
8,9,Pensacola,FL,US,HP BSM SME,NaN,Information Technology and Services,NaN,NaN,0,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,0,1,1,Full-time,Associate,NaN,0
9,10,Phoenix,AZ,US,Customer Service Associate - Part Time,NaN,Financial Services,Customer Service,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,0,1,0,Part-time,Entry level,High School or equivalent,0
10,11,Jersey City,NJ,US,ASP.net Developer Job opportunity at United St...,NaN,Information Technology and Services,Information Technology,100000-120000,1,NaN,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Benefits - FullBonus Eligible - YesInterview T...,1,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,0
11,12,London,LND,GB,Talent Sourcer (6 months fixed-term contract),HR,NaN,NaN,NaN,0,Want to build a 21st century financial service...,TransferWise is the clever new way to move mon...,We’re looking for someone who:Proven track rec...,You will join one of Europe’s most hotly tippe...,1,0,1,0,NaN,NaN,NaN,0
12,13,Stamford,CT,US,"Applications Developer, Digital",NaN,Management Consulting,Information Technology,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...","The Applications Developer, Digital will devel...",Requirements:4 – 5 years’ experience in develo...,NaN,0,0,1,0,Full-time,Associate,Bachelor's Degree,0
13,14,Orlando,FL,US,Installers,NaN,Events Services,Other,NaN,0,Growing event production company providing sta...,"Event Industry Installers Needed!! (Orlando, F...","Valid driver's license,Somewhat Clean driving ...",NaN,0,0,1,1,Full-time,Not Applicable,Unspecified,0
14,15,Sydney,NSW,AU,Account Executive - Sydney,Sales,Internet,Sales,NaN,0,Adthena is the UK’s leading competitive intell...,Are you interested in a satisfying and financi...,You’ll need to be smart and passionate and hav...,"In return we'll pay you well, give you some ow...",1,0,1,0,Full-time,Associate,Bachelor's Degree,0
15,16,Singapore,01,SG,VP of Sales - Vault Dragon,Sales,Facilities Services,Sales,120000-150000,1,Jungle Ventures is the leading Singapore based...,About Vault Dragon Vault Dragon is Dropbox for...,Key Superpowers3-5 years of high-pressure sale...,"Basic: SGD 120,000Equity negotiable for a rock...",1,0,1,1,Full-time,Executive,Bachelor's Degree,0
16,17,"Tel Aviv, Israel",,IL,Hands-On QA Leader,R&D,Internet,Engineering,NaN,0,At HoneyBook we’re re-imagining the events ind...,We are looking for a Hands-On QA Leader for ou...,Previous experience in client &amp; server tes...,NaN,0,0,1,0,Full-time,Mid-Senior level,NaN,0
17,18,Southend-on-Sea,SOS,GB,Southend-on-Sea Traineeships Under NAS 16-18 Y...,NaN,NaN,NaN,NaN,0,Established on the principles that full time e...,Government funding is only available for 16-18...,16-18 year olds only due to government funding...,Career prospects.,1,0,1,1,NaN,NaN,NaN,0
18,19,New York,NY,US,Visual Designer,NaN,NaN,NaN,NaN,0,Kettle is an independent digital agency based ...,Kettle is hiring a Visual Designer!Job Locatio...,NaN,NaN,0,0,1,0,NaN,NaN,NaN,0
19,20,USA Northeast,PA,US,Process Controls Engineer - DCS PLC MS Office ...,NaN,NaN,NaN,NaN,0,We Provide Full Time Permanent Positions for m...,Experienced Process Controls Engineer is requi...,Must have 5 or more years of experience with D...,NaN,0,0,0,0,Full-time,NaN,NaN,0
20,21,Austin,TX,US,Marketing Assistant,NaN,NaN,Marketing,NaN,0,IntelliBright was created to leverage enterpri...,IntelliBright is growing fast and is looking f...,Job RequirementsAssist in creating client onli...,NaN,0,0,1,0,NaN,NaN,NaN,0
21,22,Auckland,N,NZ,Front End Developer,NaN,Consumer Electronics,Engineering,NaN,0,Frustrated with the status quo?Like to re-imag...,Want to be part of a globally focused tech tea...,You will most likely have:A solid mastery of m...,You will be part of an awesome team of innovat...,1,0,1,0,Full-time,Mid-Senior level,Master's Degree,0
22,23,,,AE,Engagement Manager,Engagement,Telecommunications,Sales,NaN,0,Upstream’s mission is to revolutionise the way...,The position reports to the Head of Engagement...,RequirementsThe ideal candidate will be bright...,Salary &amp; BenefitsThe opportunity to learn ...,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
23,24,Carlsbad,CA,US,"Vice President, Sales and Sponsorship (Busines...",Businessfriend.com,Internet,Sales,100000-120000,1,"WDM Group is an innovative, forward thinking d...",#URL_eda2500ddcedb60957fcd7f5b164e092966f8c4e8...,"Job Requirements:A reputation as a ""go-getter""...",Businessfriend will offer a competitive six fi...,1,0,1,0,Full-time,Executive,Unspecified,0
24,25,London,LND,GB,Customer Service,NaN,NaN,NaN,NaN,0,NaN,We are a canary wharf based e-commerce company...,NaN,NaN,0,0,0,0,NaN,NaN,NaN,0
25,26,New York,NY,US,H1B SPONSOR FOR L1/L2/OPT,NaN,NaN,NaN,NaN,0,i28 Technologies has demonstrated expertise in...,"Hello,Wish you are doing good... ...","JAVA, .NET, SQL, ORACLE, SAP, Informatica, Big...",NaN,0,0,1,1,NaN,NaN,NaN,0
26,27,,,SG,Marketing Exec,Marketing,Online Media,Marketing,NaN,0,If working in a cubical seems like your idea o...,We are currently expanding our Marketing Depar...,"This position is Junior to Mid level. Ideally,...",We are looking for Singaporean residents or in...,1,0,1,0,Full-time,Associate,NaN,0
27,28,Abudhabi,AZ,AE,HAAD/DHA Licensed Doctors Opening in UAE,Medical,Hospital & Health Care,Health Care Provider,NaN,0,We the Medical Recruitment Team of Roland and ...,HAAD/DHA Licensed Doctors Opening in UAEWe the...,RequirementsEndocrinologistGastroenterologistC...,Our client is one of the reputed and leading H...,1,0,1,0,Full-time,Associate,Master's Degree,0
28,29,St. Louis,MO,US,Talent Management Process Manager,NaN,Management Consulting,NaN,NaN,0,We Provide Full Time Permanent Positions for m...,(We have more than 1500+ Job openings in our w...,NaN,NaN,0,0,0,0,Full-time,NaN,NaN,0
29,30,Toronto,ON,CA,Customer Service Associate,NaN,Consumer Services,Administrative,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 1 year custome...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
30,31,Waltham,MA,US,Customer Service Technical Specialist,NaN,Computer Software,Customer Service,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Technical Specialist will...,Qualifications:Minimum of 6 months customer se...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
31,32,,KS,US,Software Applications Specialist,NaN,Computer Software,Engineering,50000-65000,1,NaN,"Day to Day-Install, upgrade and configure web-...",Must Have's3+ years of experience with web-bas...,"Medical, Dental, Vision, Life, Disability, Pre...",1,0,1,0,Full-time,Associate,Unspecified,0
32,33,Everett,WA,US,Craftsman Associate,Field,Construction,Other,NaN,0,"We are an award-winning team of professionals,...",Construction: Entry-Level Craftsman Associate ...,Requirements: (Please do not apply if you do ...,Benefits: Hourly plus commissions. Work with ...,1,0,1,1,Full-time,Entry level,Unspecified,0
33,34,San Ramon,CA,US,Completion Engineer,NaN,Oil & Energy,Engineering,NaN,0,Valor Services provides Workforce Solutions th...,About the CompanyThis is an amazing job opport...,Education:Bachelor of Science in Petroleum Eng...,NaN,0,0,1,1,Full-time,NaN,Bachelor's Degree,0
34,35,,LND,GB,I Want To Work At Karmarama,All,Marketing and Advertising,NaN,NaN,0,At Karmarama we have a unique hiring policy: n...,Didn't see a role for you? Don't fret. We’re a...,Hey!Thanks again for applying to Karmarama and...,NaN,0,0,1,1,Full-time,NaN,NaN,0
35,36,Saint Bonaventure,NY,US,English Teacher Abroad,NaN,Education Management,NaN,NaN,0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,1,0,1,1,Contract,NaN,Bachelor's Degree,0
36,37,Yonkers,NY,US,Graduates: English Teacher Abroad,NaN,Education Management,NaN,NaN,0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it :-)Love travel...",University degree required. TEFL / TESOL / CEL...,See job description,1,0,1,0,Contract,NaN,Bachelor's Degree,0
37,38,HOUSTON,TX,US,PROJECT MANAGER,NaN,Oil & Energy,Engineering,NaN,0,NaN,we are looking for a Project Manager. The Proj...,NaN,NaN,0,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,0
38,39,Hyderabad,AP,IN,Art Director,Design,Computer Software,Design,NaN,0,"We're an emerging technology agency, and we bu...",You love clients and getting to be a conduit f...,We want you if you have:3+ years of interactiv...,Why work for Mutual Mobile? We craft beautiful...,1,0,1,1,Full-time,Mid-Senior level,NaN,0
39,40,Chicago,IL,US,Receptionist/Customer Service Technical Specia...,NaN,Financial Services,Administrative,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...","The Receptionist will be based in Chicago, IL....",Required Qualifications:High School diploma or...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
40,41,Kutztown,PA,US,English Teacher Abroad,NaN,Education Management,NaN,NaN,0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,1,0,1,1,Contract,NaN,Bachelor's Degree,0
41,42,Sacramento,CA,US,English Teacher Abroad,NaN,Education Management,NaN,NaN,0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,1,0,1,1,Contract,NaN,Bachelor's Degree,0
42,43,NaN,NaN,US,Jr. Developer,NaN,Computer Software,Engineering,40000-50000,1,NaN,Entry level Software DeveloperLocation : Atlan...,NaN,NaN,0,0,0,0,Full-time,Entry level,Bachelor's Degree,0
43,44,Columbia,MD,US,Customer Service Associate Receptionist,NaN,Consumer Services,Customer Service,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
44,45,Tulsa,OK,US,Customer Service Team Lead,NaN,Computer Software,Customer Service,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",We are currently seeking a Customer Service Te...,Required Qualifications:High school diploma or...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
45,46,Omaha,NE,US,Inside Sales Professional-Omaha,NaN,Building Materials,Sales,NaN,0,"ABC Supply Co., Inc. is the nation’s largest w...","As a Sales Representative, you will provide as...","As a Sales Representative, you must have the a...",Your benefits package as a Sales Representativ...,1,0,1,0,Full-time,NaN,NaN,0
46,47,,C,EG,Entry Level,NaN,Banking,NaN,NaN,0,History &amp; Background The Bank started its ...,We offer diversified opportunities in various ...,-0-1 years experience English Bachelor in comm...,NaN,0,0,0,0,Full-time,Entry level,Bachelor's Degree,0
47,48,Brentwood,TN,US,Customer Service Associate,NaN,Financial Services,Administrative,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:High school diploma or eq...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
48,49,Kent,OH,US,English Teacher Abroad,NaN,Education Management,NaN,NaN,0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,1,0,1,1,Contract,NaN,Bachelor's Degree,0
49,50,Dover,NH,US,Customer Service Team Lead,NaN,Facilities Services,Customer Service,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",We are currently seeking a Customer Service Te...,Required Qualifications:High school diploma or...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
50,51,Carson City,NV,US,"Food Production Manager @ PGI, a Food Producti...",Production,Food & Beverages,Production,NaN,0,PGI is a fast growing organic herb/spice/botan...,"November, 2014Pure Ground Ingredients (PGI)in ...",Manager role requirements- Multi-lingual (Engl...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
51,52,Tulsa,OK,US,Administrative/Front Desk,NaN,Education Management,Administrative,NaN,0,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Technical Specialist will...,Required Qualifications:Minimum 1 year custome...,NaN,0,0,1,0,Full-time,Entry level,High School or equivalent,0
52,53,New York,NY,US,Payroll Tax Specialist,NaN,Information Technology and Services,NaN,NaN,0,Namely is the leading end-to-end HR and payrol...,Namely is an agile startup dedicated to buildi...,Qualifications:Payroll and/or Payroll Tax proc...,NaN,0,0,1,0,Full-time,NaN,NaN,0
53,54,New York City,NY,US,Technical Project Manager,NaN,Financial Services,Information Technology,NaN,0,NaN,GBI is a growing company developing several cu...,Must have excellent oral and written communica...,"Experience with CRM, such as SugarCRM.Past emp...",1,0,0,0,Full-time,Associate,Bachelor's Degree,0
54,55,St. Cloud,MN,US,Outside Sales Professional-St. Cloud,NaN,NaN,NaN,NaN,0,"ABC Supply Co., Inc. is the nation’s largest w...","As an Outside Sales Representative, you must h...",Track Record of Sales Success – B2B or B2CNo m...,"As an Outside Sales Representative, you will r...",1,0,1,0,NaN,NaN,NaN,0
55,56,,,PL,Junior HR Marketing Manager,NaN,NaN,NaN,NaN,0,We are Netguru and we love to develop web appl...,We are Netguru and we love to develop web appl...,Great Junior HR Marketing Manager is a person ...,Perks &amp; benefits:co-financing internationa...,1,0,1,1,NaN,NaN,NaN,0
56,57,Oronoco,MN,US,Outside Sales Professional-Oronoco,NaN,NaN,NaN,NaN,0,"ABC Supply Co., Inc. is the nation’s largest w...","As an Outside Sales Representative, you must h...",Track Record of Sales Success – B2B or B2CNo m...,"As an Outside Sales Representative, you will r...",1,0,1,0,NaN,NaN,NaN,0
57,58,Ottawa,ON,CA,Intensive Case Management Worker (Bilingual Es...,ICM,Hospital & Health Care,NaN,NaN,0,Since 1973: Working together to make our commu...,Internal/External Employment OpportunityPositi...,Education and LanguageA bachelor's degree in c...,Sandy Hill Community Health Centre offers empl...,1,0,1,1,NaN,NaN,Bachelor's Degree,0
58,59,Fort Worth,TX,US,Marketing Guru,NaN,Computer Software,Marketing,NaN,0,We're a Fort Worth based startup trying to cha...,We're a Fort Worth based startup trying to cha...,You've got: 3 - 5 years of technology or healt...,"And for your efforts, we happily provide: A co...",1,0,1,0,Full-time,Associate,Bachelor's Degree,0
59,60,San Francisco,CA,US,Product Visual Designer,NaN,Information Technology and Services,Design,NaN,0,"From the lands of Can Do, Roll Our Sleeves Up ...",Apcera is revolutionizing enterprise technolog...,RESPONSIBILITIES:Work with the UX architect's ...,Competitive salary &amp; equityGreat location ...,1,0,1,1,Full-time,Not Applicable,Unspecified,0

In [82]:
list(df.columns)

['job_id',
 'city',
 'state/province',
 'country',
 'title',
 'department',
 'industry',
 'function',
 'salary_range',
 'salary_provided',
 'company_profile',
 'description',
 'requirements',
 'benefits',
 'benefits_provided',
 'telecommuting',
 'has_company_logo',
 'has_questions',
 'employment_type',
 'required_experience',
 'required_education',
 'fraudulent']

# Feature Selection

In [83]:
# Feature Selection
selected_features = df.drop(['job_id', 'city', 'state/province', 'country','title','department', 'salary_range', 
                             'company_profile', 'description', 'requirements','benefits', 'fraudulent'], axis=1)
selected_features

,industry,function,salary_provided,benefits_provided,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education
0,NaN,Marketing,0,0,0,1,0,Other,Internship,NaN
1,Marketing and Advertising,Customer Service,0,1,0,1,0,Full-time,Not Applicable,NaN
2,NaN,NaN,0,0,0,1,0,NaN,NaN,NaN
3,Computer Software,Sales,0,1,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree
4,Hospital & Health Care,Health Care Provider,0,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree
...,...,...,...,...,...,...,...,...,...,...
17875,Computer Software,Sales,0,1,0,1,1,Full-time,Mid-Senior level,NaN
17876,Internet,Accounting/Auditing,0,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree
17877,NaN,NaN,0,0,0,0,0,Full-time,NaN,NaN
17878,Graphic Design,Design,0,1,0,0,1,Contract,Not Applicable,Professional
17879,Computer Software,Engineering,0,0,0,1,1,Full-time,Mid-Senior level,NaN

In [84]:
# Get Dummies for Categorical Columns
dummy_features = pd.get_dummies(selected_features)
dummy_features

,salary_provided,benefits_provided,telecommuting,has_company_logo,has_questions,industry_Accounting,industry_Airlines/Aviation,industry_Alternative Dispute Resolution,industry_Animation,industry_Apparel & Fashion,industry_Architecture & Planning,industry_Automotive,industry_Aviation & Aerospace,industry_Banking,industry_Biotechnology,...,required_experience_Mid-Senior level,required_experience_Not Applicable,required_education_Associate Degree,required_education_Bachelor's Degree,required_education_Certification,required_education_Doctorate,required_education_High School or equivalent,required_education_Master's Degree,required_education_Professional,required_education_Some College Coursework Completed,required_education_Some High School Coursework,required_education_Unspecified,required_education_Vocational,required_education_Vocational - Degree,required_education_Vocational - HS Diploma
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17876,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
17877,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17878,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
17879,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [85]:
print(len(list(dummy_features.columns)))
list(dummy_features.columns)

198

['salary_provided',
 'benefits_provided',
 'telecommuting',
 'has_company_logo',
 'has_questions',
 'industry_Accounting',
 'industry_Airlines/Aviation',
 'industry_Alternative Dispute Resolution',
 'industry_Animation',
 'industry_Apparel & Fashion',
 'industry_Architecture & Planning',
 'industry_Automotive',
 'industry_Aviation & Aerospace',
 'industry_Banking',
 'industry_Biotechnology',
 'industry_Broadcast Media',
 'industry_Building Materials',
 'industry_Business Supplies and Equipment',
 'industry_Capital Markets',
 'industry_Chemicals',
 'industry_Civic & Social Organization',
 'industry_Civil Engineering',
 'industry_Commercial Real Estate',
 'industry_Computer & Network Security',
 'industry_Computer Games',
 'industry_Computer Hardware',
 'industry_Computer Networking',
 'industry_Computer Software',
 'industry_Construction',
 'industry_Consumer Electronics',
 'industry_Consumer Goods',
 'industry_Consumer Services',
 'industry_Cosmetics',
 'industry_Defense & Space',
 'industry_Design',
 'industry_E-Learning',
 'industry_Education Management',
 'industry_Electrical/Electronic Manufacturing',
 'industry_Entertainment',
 'industry_Environmental Services',
 'industry_Events Services',
 'industry_Executive Office',
 'industry_Facilities Services',
 'industry_Farming',
 'industry_Financial Services',
 'industry_Fishery',
 'industry_Food & Beverages',
 'industry_Food Production',
 'industry_Fund-Raising',
 'industry_Furniture',
 'industry_Gambling & Casinos',
 'industry_Government Administration',
 'industry_Government Relations',
 'industry_Graphic Design',
 'industry_Health, Wellness and Fitness',
 'industry_Higher Education',
 'industry_Hospital & Health Care',
 'industry_Hospitality',
 'industry_Human Resources',
 'industry_Import and Export',
 'industry_Individual & Family Services',
 'industry_Industrial Automation',
 'industry_Information Services',
 'industry_Information Technology and Services',
 'industry_Insurance',
 'industry_International Trade and Development',
 'industry_Internet',
 'industry_Investment Banking',
 'industry_Investment Management',
 'industry_Law Enforcement',
 'industry_Law Practice',
 'industry_Legal Services',
 'industry_Leisure, Travel & Tourism',
 'industry_Libraries',
 'industry_Logistics and Supply Chain',
 'industry_Luxury Goods & Jewelry',
 'industry_Machinery',
 'industry_Management Consulting',
 'industry_Maritime',
 'industry_Market Research',
 'industry_Marketing and Advertising',
 'industry_Mechanical or Industrial Engineering',
 'industry_Media Production',
 'industry_Medical Devices',
 'industry_Medical Practice',
 'industry_Mental Health Care',
 'industry_Military',
 'industry_Mining & Metals',
 'industry_Motion Pictures and Film',
 'industry_Museums and Institutions',
 'industry_Music',
 'industry_Nanotechnology',
 'industry_Nonprofit Organization Management',
 'industry_Oil & Energy',
 'industry_Online Media',
 'industry_Outsourcing/Offshoring',
 'industry_Package/Freight Delivery',
 'industry_Packaging and Containers',
 'industry_Performing Arts',
 'industry_Pharmaceuticals',
 'industry_Philanthropy',
 'industry_Photography',
 'industry_Plastics',
 'industry_Primary/Secondary Education',
 'industry_Printing',
 'industry_Professional Training & Coaching',
 'industry_Program Development',
 'industry_Public Policy',
 'industry_Public Relations and Communications',
 'industry_Public Safety',
 'industry_Publishing',
 'industry_Ranching',
 'industry_Real Estate',
 'industry_Religious Institutions',
 'industry_Renewables & Environment',
 'industry_Research',
 'industry_Restaurants',
 'industry_Retail',
 'industry_Security and Investigations',
 'industry_Semiconductors',
 'industry_Shipbuilding',
 'industry_Sporting Goods',
 'industry_Sports',
 'industry_Staffing and Recruiting',
 'industry_Telecommunications',
 'industry_Textiles',
 'industry_Translation and Localization',
 'industry_Transportation/Trucking/Railroad',
 'industry_Utilities',
 'industry_Venture Capital & Private Equity',
 'industry_Veterinary',
 'industry_Warehousing',
 'industry_Wholesale',
 'industry_Wine and Spirits',
 'industry_Wireless',
 'industry_Writing and Editing',
 'function_Accounting/Auditing',
 'function_Administrative',
 'function_Advertising',
 'function_Art/Creative',
 'function_Business Analyst',
 'function_Business Development',
 'function_Consulting',
 'function_Customer Service',
 'function_Data Analyst',
 'function_Design',
 'function_Distribution',
 'function_Education',
 'function_Engineering',
 'function_Finance',
 'function_Financial Analyst',
 'function_General Business',
 'function_Health Care Provider',
 'function_Human Resources',
 'function_Information Technology',
 'function_Legal',
 'function_Management',
 'function_Manufacturing',
 'function_Marketing',
 'function_Other',
 'function_Product Management',
 'function_Production',
 'function_Project Management',
 'function_Public Relations',
 'function_Purchasing',
 'function_Quality Assurance',
 'function_Research',
 'function_Sales',
 'function_Science',
 'function_Strategy/Planning',
 'function_Supply Chain',
 'function_Training',
 'function_Writing/Editing',
 'employment_type_Contract',
 'employment_type_Full-time',
 'employment_type_Other',
 'employment_type_Part-time',
 'employment_type_Temporary',
 'required_experience_Associate',
 'required_experience_Director',
 'required_experience_Entry level',
 'required_experience_Executive',
 'required_experience_Internship',
 'required_experience_Mid-Senior level',
 'required_experience_Not Applicable',
 'required_education_Associate Degree',
 "required_education_Bachelor's Degree",
 'required_education_Certification',
 'required_education_Doctorate',
 'required_education_High School or equivalent',
 "required_education_Master's Degree",
 'required_education_Professional',
 'required_education_Some College Coursework Completed',
 'required_education_Some High School Coursework',
 'required_education_Unspecified',
 'required_education_Vocational',
 'required_education_Vocational - Degree',
 'required_education_Vocational - HS Diploma']

In [86]:
# Assign the data to X and y
X = dummy_features
y = df['fraudulent']

print(X.shape, y.shape)

(17880, 198) (17880,)

In [87]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=22)

# Pre-Processing

Scale Data using the MinMaxScaler

In [88]:
# Scale the data using the MinMaxScaler
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Train the Model

In [89]:
#Random Forest algorithm
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200, random_state=22)

#Fit the model to the data
rf = rf.fit(X_train_scaled, y_train)

#Quantify the model
rf.score(X_test_scaled, y_test)

0.9731543624161074

In [90]:
# Check Feature Importance
sorted(zip(rf.feature_importances_, selected_features), reverse=True)

[(0.1081341299200165, 'benefits_provided'),
 (0.04730574788324089, 'telecommuting'),
 (0.041169391297885945, 'function'),
 (0.03391593964321584, 'industry'),
 (0.024830148802186883, 'has_company_logo'),
 (0.013376730608443532, 'salary_provided'),
 (0.001295034301165924, 'required_experience'),
 (0.0012035381533776262, 'has_questions'),
 (0.001118000545029267, 'required_education'),
 (0.0, 'employment_type')]

In [98]:
# Classification Model
from sklearn.metrics import classification_report
predictions = rf.predict(X_test)
print("RF Classification Report: \n" + classification_report(y_test, predictions, target_names=['real','fake']))

RF Classification Report:
              precision    recall  f1-score   support

        real       0.97      1.00      0.99      4251
        fake       0.91      0.50      0.65       219

    accuracy                           0.97      4470
   macro avg       0.94      0.75      0.82      4470
weighted avg       0.97      0.97      0.97      4470

# Hyperparameter Tuning

In [92]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = { 
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

CV_rf = GridSearchCV(estimator=rf, param_grid=param_grid, cv= 5)

In [93]:
# Train the model with GridSearch
CV_rf.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=200, n_jobs=None,
                                              oob_score=False, random_state=22,
                                              verbose=0, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [200, 500]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [94]:
#Get best params
print(CV_rf.best_params_)
print(CV_rf.best_score_)

{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 200}
0.9538404175988069

In [95]:
#Create new RF model with best params
rf2 = RandomForestClassifier(random_state=22, max_features='auto', n_estimators= 200, max_depth=8, criterion='gini')

#Fit the model to the data
rf2 = rf2.fit(X_train_scaled, y_train)

#Quantify the model
rf2.score(X_test_scaled, y_test)

0.9525727069351231

In [96]:
# Classification Model
from sklearn.metrics import classification_report
predictions = rf2.predict(X_test)
print("RF2 Classification Report: \n" + classification_report(y_test, predictions, target_names=['real','fake']))

RF2 Classification Report:
              precision    recall  f1-score   support

        real       0.95      1.00      0.98      4251
        fake       1.00      0.03      0.06       219

    accuracy                           0.95      4470
   macro avg       0.98      0.52      0.52      4470
weighted avg       0.95      0.95      0.93      4470

# Save the Model

In [97]:
import joblib
joblib.dump(rf2, 'nontext_rf2.h5')

['nontext_rf2.h5']