# Load Data

In [0]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 30)
from time import time

import warnings
warnings.filterwarnings("ignore")

In [0]:
# Read in csv file
url = "https://job-postings-dataviz.s3.amazonaws.com/fake_jobs_clean.csv"
df = pd.read_csv(url, sep=",",  encoding = "UTF-8" )
# or to read for the data folder directly
# df = pd.read_csv("../assets/data/fake_jobs_clean.csv")
# df.head(60)

In [3]:
list(df.columns)

['job_id',
 'city',
 'state/province',
 'country',
 'title',
 'department',
 'industry',
 'function',
 'salary_range',
 'salary_provided',
 'company_profile',
 'description',
 'requirements',
 'benefits',
 'benefits_provided',
 'telecommuting',
 'has_company_logo',
 'has_questions',
 'employment_type',
 'required_experience',
 'required_education',
 'fraudulent']

# Feature Selection

In [4]:
# Feature Selection
selected_features = df.drop(['job_id', 'city', 'state/province', 'country','title','department', 'salary_range', 
                             'company_profile', 'description', 'requirements','benefits', 'fraudulent'], axis=1)
selected_features

,industry,function,salary_provided,benefits_provided,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education
0,NaN,Marketing,0,0,0,1,0,Other,Internship,NaN
1,Marketing and Advertising,Customer Service,0,1,0,1,0,Full-time,Not Applicable,NaN
2,NaN,NaN,0,0,0,1,0,NaN,NaN,NaN
3,Computer Software,Sales,0,1,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree
4,Hospital & Health Care,Health Care Provider,0,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree
...,...,...,...,...,...,...,...,...,...,...
17875,Computer Software,Sales,0,1,0,1,1,Full-time,Mid-Senior level,NaN
17876,Internet,Accounting/Auditing,0,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree
17877,NaN,NaN,0,0,0,0,0,Full-time,NaN,NaN
17878,Graphic Design,Design,0,1,0,0,1,Contract,Not Applicable,Professional
17879,Computer Software,Engineering,0,0,0,1,1,Full-time,Mid-Senior level,NaN

In [6]:
# Get Dummies for Categorical Columns
dummy_features = pd.get_dummies(selected_features)
dummy_features

,salary_provided,benefits_provided,telecommuting,has_company_logo,has_questions,industry_Accounting,industry_Airlines/Aviation,industry_Alternative Dispute Resolution,industry_Animation,industry_Apparel & Fashion,industry_Architecture & Planning,industry_Automotive,industry_Aviation & Aerospace,industry_Banking,industry_Biotechnology,...,required_experience_Mid-Senior level,required_experience_Not Applicable,required_education_Associate Degree,required_education_Bachelor's Degree,required_education_Certification,required_education_Doctorate,required_education_High School or equivalent,required_education_Master's Degree,required_education_Professional,required_education_Some College Coursework Completed,required_education_Some High School Coursework,required_education_Unspecified,required_education_Vocational,required_education_Vocational - Degree,required_education_Vocational - HS Diploma
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17876,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
17877,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17878,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
17879,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
print(len(list(dummy_features.columns)))
list(dummy_features.columns)

198

['salary_provided',
 'benefits_provided',
 'telecommuting',
 'has_company_logo',
 'has_questions',
 'industry_Accounting',
 'industry_Airlines/Aviation',
 'industry_Alternative Dispute Resolution',
 'industry_Animation',
 'industry_Apparel & Fashion',
 'industry_Architecture & Planning',
 'industry_Automotive',
 'industry_Aviation & Aerospace',
 'industry_Banking',
 'industry_Biotechnology',
 'industry_Broadcast Media',
 'industry_Building Materials',
 'industry_Business Supplies and Equipment',
 'industry_Capital Markets',
 'industry_Chemicals',
 'industry_Civic & Social Organization',
 'industry_Civil Engineering',
 'industry_Commercial Real Estate',
 'industry_Computer & Network Security',
 'industry_Computer Games',
 'industry_Computer Hardware',
 'industry_Computer Networking',
 'industry_Computer Software',
 'industry_Construction',
 'industry_Consumer Electronics',
 'industry_Consumer Goods',
 'industry_Consumer Services',
 'industry_Cosmetics',
 'industry_Defense & Space',
 'industry_Design',
 'industry_E-Learning',
 'industry_Education Management',
 'industry_Electrical/Electronic Manufacturing',
 'industry_Entertainment',
 'industry_Environmental Services',
 'industry_Events Services',
 'industry_Executive Office',
 'industry_Facilities Services',
 'industry_Farming',
 'industry_Financial Services',
 'industry_Fishery',
 'industry_Food & Beverages',
 'industry_Food Production',
 'industry_Fund-Raising',
 'industry_Furniture',
 'industry_Gambling & Casinos',
 'industry_Government Administration',
 'industry_Government Relations',
 'industry_Graphic Design',
 'industry_Health, Wellness and Fitness',
 'industry_Higher Education',
 'industry_Hospital & Health Care',
 'industry_Hospitality',
 'industry_Human Resources',
 'industry_Import and Export',
 'industry_Individual & Family Services',
 'industry_Industrial Automation',
 'industry_Information Services',
 'industry_Information Technology and Services',
 'industry_Insurance',
 'industry_International Trade and Development',
 'industry_Internet',
 'industry_Investment Banking',
 'industry_Investment Management',
 'industry_Law Enforcement',
 'industry_Law Practice',
 'industry_Legal Services',
 'industry_Leisure, Travel & Tourism',
 'industry_Libraries',
 'industry_Logistics and Supply Chain',
 'industry_Luxury Goods & Jewelry',
 'industry_Machinery',
 'industry_Management Consulting',
 'industry_Maritime',
 'industry_Market Research',
 'industry_Marketing and Advertising',
 'industry_Mechanical or Industrial Engineering',
 'industry_Media Production',
 'industry_Medical Devices',
 'industry_Medical Practice',
 'industry_Mental Health Care',
 'industry_Military',
 'industry_Mining & Metals',
 'industry_Motion Pictures and Film',
 'industry_Museums and Institutions',
 'industry_Music',
 'industry_Nanotechnology',
 'industry_Nonprofit Organization Management',
 'industry_Oil & Energy',
 'industry_Online Media',
 'industry_Outsourcing/Offshoring',
 'industry_Package/Freight Delivery',
 'industry_Packaging and Containers',
 'industry_Performing Arts',
 'industry_Pharmaceuticals',
 'industry_Philanthropy',
 'industry_Photography',
 'industry_Plastics',
 'industry_Primary/Secondary Education',
 'industry_Printing',
 'industry_Professional Training & Coaching',
 'industry_Program Development',
 'industry_Public Policy',
 'industry_Public Relations and Communications',
 'industry_Public Safety',
 'industry_Publishing',
 'industry_Ranching',
 'industry_Real Estate',
 'industry_Religious Institutions',
 'industry_Renewables & Environment',
 'industry_Research',
 'industry_Restaurants',
 'industry_Retail',
 'industry_Security and Investigations',
 'industry_Semiconductors',
 'industry_Shipbuilding',
 'industry_Sporting Goods',
 'industry_Sports',
 'industry_Staffing and Recruiting',
 'industry_Telecommunications',
 'industry_Textiles',
 'industry_Translation and Localization',
 'industry_Transportation/Trucking/Railroad',
 'industry_Utilities',
 'industry_Venture Capital & Private Equity',
 'industry_Veterinary',
 'industry_Warehousing',
 'industry_Wholesale',
 'industry_Wine and Spirits',
 'industry_Wireless',
 'industry_Writing and Editing',
 'function_Accounting/Auditing',
 'function_Administrative',
 'function_Advertising',
 'function_Art/Creative',
 'function_Business Analyst',
 'function_Business Development',
 'function_Consulting',
 'function_Customer Service',
 'function_Data Analyst',
 'function_Design',
 'function_Distribution',
 'function_Education',
 'function_Engineering',
 'function_Finance',
 'function_Financial Analyst',
 'function_General Business',
 'function_Health Care Provider',
 'function_Human Resources',
 'function_Information Technology',
 'function_Legal',
 'function_Management',
 'function_Manufacturing',
 'function_Marketing',
 'function_Other',
 'function_Product Management',
 'function_Production',
 'function_Project Management',
 'function_Public Relations',
 'function_Purchasing',
 'function_Quality Assurance',
 'function_Research',
 'function_Sales',
 'function_Science',
 'function_Strategy/Planning',
 'function_Supply Chain',
 'function_Training',
 'function_Writing/Editing',
 'employment_type_Contract',
 'employment_type_Full-time',
 'employment_type_Other',
 'employment_type_Part-time',
 'employment_type_Temporary',
 'required_experience_Associate',
 'required_experience_Director',
 'required_experience_Entry level',
 'required_experience_Executive',
 'required_experience_Internship',
 'required_experience_Mid-Senior level',
 'required_experience_Not Applicable',
 'required_education_Associate Degree',
 "required_education_Bachelor's Degree",
 'required_education_Certification',
 'required_education_Doctorate',
 'required_education_High School or equivalent',
 "required_education_Master's Degree",
 'required_education_Professional',
 'required_education_Some College Coursework Completed',
 'required_education_Some High School Coursework',
 'required_education_Unspecified',
 'required_education_Vocational',
 'required_education_Vocational - Degree',
 'required_education_Vocational - HS Diploma']

In [8]:
# Assign the data to X and y
X = dummy_features.values
y = df.iloc[:,21].values

print(X.shape, y.shape)

(17880, 198) (17880,)

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=22)

# Pre-Processing

Scale Data using the MinMaxScaler

In [0]:
# Scale the data using the MinMaxScaler
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [0]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [24]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
y_train_categorical.shape

(13410, 2)

# Train the Model

In [0]:
#Create a deep learning model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=198))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [0]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 100)               19900
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 202
=================================================================
Total params: 30,202
Trainable params: 30,202
Non-trainable params: 0
_________________________________________________________________

In [28]:
# Fit the model

# Time duration of model fit 
t1_start = time()
model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2)

t1_stop = time() 
print("Stop/Start Time:", t1_stop, t1_start)   
print(f'Duration of Model in seconds:',t1_stop-t1_start)

Epoch 1/100
420/420 - 1s - loss: 0.1562 - accuracy: 0.9531
Epoch 2/100
420/420 - 1s - loss: 0.1012 - accuracy: 0.9670
Epoch 3/100
420/420 - 1s - loss: 0.0831 - accuracy: 0.9735
Epoch 4/100
420/420 - 1s - loss: 0.0726 - accuracy: 0.9761
Epoch 5/100
420/420 - 1s - loss: 0.0647 - accuracy: 0.9786
Epoch 6/100
420/420 - 1s - loss: 0.0624 - accuracy: 0.9793
Epoch 7/100
420/420 - 1s - loss: 0.0585 - accuracy: 0.9808
Epoch 8/100
420/420 - 1s - loss: 0.0552 - accuracy: 0.9820
Epoch 9/100
420/420 - 1s - loss: 0.0537 - accuracy: 0.9823
Epoch 10/100
420/420 - 1s - loss: 0.0523 - accuracy: 0.9817
Epoch 11/100
420/420 - 1s - loss: 0.0513 - accuracy: 0.9829
Epoch 12/100
420/420 - 1s - loss: 0.0514 - accuracy: 0.9826
Epoch 13/100
420/420 - 1s - loss: 0.0496 - accuracy: 0.9826
Epoch 14/100
420/420 - 1s - loss: 0.0479 - accuracy: 0.9835
Epoch 15/100
420/420 - 1s - loss: 0.0486 - accuracy: 0.9837
Epoch 16/100
420/420 - 1s - loss: 0.0478 - accuracy: 0.9835
Epoch 17/100
420/420 - 1s - loss: 0.0472 - accuracy: 0.9837
Epoch 18/100
420/420 - 1s - loss: 0.0465 - accuracy: 0.9834
Epoch 19/100
420/420 - 1s - loss: 0.0465 - accuracy: 0.9840
Epoch 20/100
420/420 - 1s - loss: 0.0452 - accuracy: 0.9838
Epoch 21/100
420/420 - 1s - loss: 0.0451 - accuracy: 0.9846
Epoch 22/100
420/420 - 1s - loss: 0.0451 - accuracy: 0.9837
Epoch 23/100
420/420 - 1s - loss: 0.0446 - accuracy: 0.9846
Epoch 24/100
420/420 - 1s - loss: 0.0444 - accuracy: 0.9840
Epoch 25/100
420/420 - 1s - loss: 0.0446 - accuracy: 0.9843
Epoch 26/100
420/420 - 1s - loss: 0.0441 - accuracy: 0.9841
Epoch 27/100
420/420 - 1s - loss: 0.0438 - accuracy: 0.9845
Epoch 28/100
420/420 - 1s - loss: 0.0439 - accuracy: 0.9845
Epoch 29/100
420/420 - 1s - loss: 0.0439 - accuracy: 0.9844
Epoch 30/100
420/420 - 1s - loss: 0.0437 - accuracy: 0.9848
Epoch 31/100
420/420 - 1s - loss: 0.0439 - accuracy: 0.9842
Epoch 32/100
420/420 - 1s - loss: 0.0428 - accuracy: 0.9846
Epoch 33/100
420/420 - 1s - loss: 0.0429 - accuracy: 0.9845
Epoch 34/100
420/420 - 1s - loss: 0.0429 - accuracy: 0.9846
Epoch 35/100
420/420 - 1s - loss: 0.0425 - accuracy: 0.9848
Epoch 36/100
420/420 - 1s - loss: 0.0432 - accuracy: 0.9842
Epoch 37/100
420/420 - 1s - loss: 0.0433 - accuracy: 0.9843
Epoch 38/100
420/420 - 1s - loss: 0.0416 - accuracy: 0.9847
Epoch 39/100
420/420 - 1s - loss: 0.0421 - accuracy: 0.9846
Epoch 40/100
420/420 - 1s - loss: 0.0423 - accuracy: 0.9847
Epoch 41/100
420/420 - 1s - loss: 0.0421 - accuracy: 0.9846
Epoch 42/100
420/420 - 1s - loss: 0.0428 - accuracy: 0.9846
Epoch 43/100
420/420 - 1s - loss: 0.0421 - accuracy: 0.9846
Epoch 44/100
420/420 - 1s - loss: 0.0415 - accuracy: 0.9848
Epoch 45/100
420/420 - 1s - loss: 0.0420 - accuracy: 0.9847
Epoch 46/100
420/420 - 1s - loss: 0.0418 - accuracy: 0.9849
Epoch 47/100
420/420 - 1s - loss: 0.0412 - accuracy: 0.9846
Epoch 48/100
420/420 - 1s - loss: 0.0416 - accuracy: 0.9848
Epoch 49/100
420/420 - 1s - loss: 0.0413 - accuracy: 0.9847
Epoch 50/100
420/420 - 1s - loss: 0.0417 - accuracy: 0.9849
Epoch 51/100
420/420 - 1s - loss: 0.0417 - accuracy: 0.9851
Epoch 52/100
420/420 - 1s - loss: 0.0413 - accuracy: 0.9849
Epoch 53/100
420/420 - 1s - loss: 0.0411 - accuracy: 0.9849
Epoch 54/100
420/420 - 1s - loss: 0.0416 - accuracy: 0.9846
Epoch 55/100
420/420 - 1s - loss: 0.0411 - accuracy: 0.9847
Epoch 56/100
420/420 - 1s - loss: 0.0410 - accuracy: 0.9848
Epoch 57/100
420/420 - 1s - loss: 0.0409 - accuracy: 0.9849
Epoch 58/100
420/420 - 1s - loss: 0.0411 - accuracy: 0.9846
Epoch 59/100
420/420 - 1s - loss: 0.0409 - accuracy: 0.9849
Epoch 60/100
420/420 - 1s - loss: 0.0449 - accuracy: 0.9850
Epoch 61/100
420/420 - 1s - loss: 0.0410 - accuracy: 0.9851
Epoch 62/100
420/420 - 1s - loss: 0.0407 - accuracy: 0.9852
Epoch 63/100
420/420 - 1s - loss: 0.0406 - accuracy: 0.9849
Epoch 64/100
420/420 - 1s - loss: 0.0405 - accuracy: 0.9848
Epoch 65/100
420/420 - 1s - loss: 0.0406 - accuracy: 0.9849
Epoch 66/100
420/420 - 1s - loss: 0.0410 - accuracy: 0.9852
Epoch 67/100
420/420 - 1s - loss: 0.0405 - accuracy: 0.9852
Epoch 68/100
420/420 - 1s - loss: 0.0408 - accuracy: 0.9852
Epoch 69/100
420/420 - 1s - loss: 0.0409 - accuracy: 0.9849
Epoch 70/100
420/420 - 1s - loss: 0.0412 - accuracy: 0.9851
Epoch 71/100
420/420 - 1s - loss: 0.0410 - accuracy: 0.9850
Epoch 72/100
420/420 - 1s - loss: 0.0418 - accuracy: 0.9847
Epoch 73/100
420/420 - 1s - loss: 0.0404 - accuracy: 0.9848
Epoch 74/100
420/420 - 1s - loss: 0.0402 - accuracy: 0.9854
Epoch 75/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9852
Epoch 76/100
420/420 - 1s - loss: 0.0405 - accuracy: 0.9850
Epoch 77/100
420/420 - 1s - loss: 0.0401 - accuracy: 0.9852
Epoch 78/100
420/420 - 1s - loss: 0.0403 - accuracy: 0.9852
Epoch 79/100
420/420 - 1s - loss: 0.0402 - accuracy: 0.9850
Epoch 80/100
420/420 - 1s - loss: 0.0434 - accuracy: 0.9853
Epoch 81/100
420/420 - 1s - loss: 0.0406 - accuracy: 0.9855
Epoch 82/100
420/420 - 1s - loss: 0.0406 - accuracy: 0.9852
Epoch 83/100
420/420 - 1s - loss: 0.0403 - accuracy: 0.9849
Epoch 84/100
420/420 - 1s - loss: 0.0402 - accuracy: 0.9849
Epoch 85/100
420/420 - 1s - loss: 0.0416 - accuracy: 0.9852
Epoch 86/100
420/420 - 1s - loss: 0.0408 - accuracy: 0.9849
Epoch 87/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9853
Epoch 88/100
420/420 - 1s - loss: 0.0400 - accuracy: 0.9850
Epoch 89/100
420/420 - 1s - loss: 0.0405 - accuracy: 0.9850
Epoch 90/100
420/420 - 1s - loss: 0.0418 - accuracy: 0.9852
Epoch 91/100
420/420 - 1s - loss: 0.0400 - accuracy: 0.9852
Epoch 92/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9852
Epoch 93/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9852
Epoch 94/100
420/420 - 1s - loss: 0.0398 - accuracy: 0.9852
Epoch 95/100
420/420 - 1s - loss: 0.0400 - accuracy: 0.9852
Epoch 96/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9854
Epoch 97/100
420/420 - 1s - loss: 0.0404 - accuracy: 0.9851
Epoch 98/100
420/420 - 1s - loss: 0.0413 - accuracy: 0.9847
Epoch 99/100
420/420 - 1s - loss: 0.0399 - accuracy: 0.9854
Epoch 100/100
420/420 - 1s - loss: 0.0398 - accuracy: 0.9853
Stop/Start Time: 1587087600.5283616 1587087536.503983
Duration of Model in Nanoseconds: 64.02437853813171

In [29]:
# Quantify the model
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

140/140 - 0s - loss: 0.2154 - accuracy: 0.9734
Loss: 0.21536073088645935, Accuracy: 0.97337806224823

In [0]:
predictions = model.predict(X_test_scaled)
predictions = np.around(predictions , decimals = 0)

In [31]:
predictions

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [32]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test_categorical, predictions,
                            target_names= ["real", "fake"]))

              precision    recall  f1-score   support

        real       0.98      1.00      0.99      4251
        fake       0.86      0.55      0.67       219

   micro avg       0.97      0.97      0.97      4470
   macro avg       0.92      0.77      0.83      4470
weighted avg       0.97      0.97      0.97      4470
 samples avg       0.97      0.97      0.97      4470

# Save the Model

In [0]:
# import joblib
# joblib.dump(model, 'nontext_deeplearning_model.h5')